routes/web.php
<?php

//Views
Route::get('/', 'HomeController@ShowHome');

Route::view('/nosotros','about');

Route::get('/servicios','ServiceController@ShowViewServices');

Route::get('/portafolio','ProjectController@ShowPortfolio');

Route::get('/blog','BlogController@ShowViewPosts');

Route::get('/blog/{slug}','BlogController@ShowViewPost');

Route::get('/contactanos','ContactUSController@contactUS');
Route::post('/contactanos/store','ContactUSController@contactUSPost');

//Views Manager

//Route::get('/', 'UserController@ShowSubscribe');

//Route::post('/fwasdevelopers/admin-manager/subscribe/store','UserController@StoreSubscribe');

Route::group(['middleware' => ['auth']], function() {
Route::get('/fwasdevelopers/admin-manager','UserController@AdminPanel');
Route::get('/fwasdevelopers/admin-manager/manager-projects/app-mobile','UserController@AdminAppMobile');

Route::get('/fwasdevelopers/admin-manager/services','ServiceController@ShowServices');
Route::get('/fwasdevelopers/admin-manager/services/create','ServiceController@CreateService');
Route::post('/fwasdevelopers/admin-manager/services/store','ServiceController@StoreService');
Route::get('/fwasdevelopers/admin-manager/services/edit/{id}','ServiceController@EditService');
Route::post('/fwasdevelopers/admin-manager/services/update/{id}','ServiceController@UpdateService');
Route::get('/fwasdevelopers/admin-manager/services/delete/{id}','ServiceController@DestroyService');

Route::get('/fwasdevelopers/admin-manager/users','UserController@ShowUsers');
Route::get('/fwasdevelopers/admin-manager/users/create','UserController@CreateUser');
Route::post('/fwasdevelopers/admin-manager/users/store','UserController@StoreUser');
Route::get('/fwasdevelopers/admin-manager/users/edit/{id}','UserController@EditUser');
Route::post('/fwasdevelopers/admin-manager/users/update/{id}','UserController@UpdateUser');
Route::get('/fwasdevelopers/admin-manager/users/delete/{id}','UserController@DestroyUser');

Route::get('/fwasdevelopers/admin-manager/projects','ProjectController@ShowProjects');
Route::get('/fwasdevelopers/admin-manager/projects/create','ProjectController@CreateProject');
Route::post('/fwasdevelopers/admin-manager/projects/store','ProjectController@StoreProject');
Route::get('/fwasdevelopers/admin-manager/projects/edit/{id}','ProjectController@EditProject');
Route::post('/fwasdevelopers/admin-manager/projects/update/{id}','ProjectController@UpdateProject');
Route::get('/fwasdevelopers/admin-manager/projects/delete/{id}','ProjectController@DestroyProject');

Route::get('/fwasdevelopers/admin-manager/posts','BlogController@ShowPosts');
Route::get('/fwasdevelopers/admin-manager/posts/create','BlogController@CreatePost');
Route::post('/fwasdevelopers/admin-manager/posts/store','BlogController@StorePost');
Route::get('/fwasdevelopers/admin-manager/posts/edit/{id}','BlogController@EditPost');
Route::post('/fwasdevelopers/admin-manager/posts/update/{id}','BlogController@UpdatePost');
Route::get('/fwasdevelopers/admin-manager/posts/delete/{id}','BlogController@DestroyPost');


Route::get('/fwasdevelopers/admin-manager/sliders','SliderController@ShowSliders');
Route::get('/fwasdevelopers/admin-manager/sliders/create','SliderController@CreateSlider');
Route::post('/fwasdevelopers/admin-manager/sliders/store','SliderController@StoreSlider');
Route::get('/fwasdevelopers/admin-manager/sliders/edit/{id}','SliderController@EditSlider');
Route::post('/fwasdevelopers/admin-manager/sliders/update/{id}','SliderController@UpdateSlider');
Route::get('/fwasdevelopers/admin-manager/sliders/delete/{id}','SliderController@DestroySlider');

Route::get('/fwasdevelopers/admin-manager/detail-sliders','DetailSliderController@ShowDetailSliders');
Route::get('/fwasdevelopers/admin-manager/detail-sliders/create','DetailSliderController@CreateDetailSlider');
Route::post('/fwasdevelopers/admin-manager/detail-sliders/store','DetailSliderController@StoreDetailSlider');
Route::get('/fwasdevelopers/admin-manager/detail-sliders/edit/{id}','DetailSliderController@EditDetailSlider');
Route::post('/fwasdevelopers/admin-manager/detail-sliders/update/{id}','DetailSliderController@UpdateDetailSlider');
Route::get('/fwasdevelopers/admin-manager/detail-sliders/delete/{id}','DetailSliderController@DestroyDetailSlider');

//Routes Manager-Projects

//Routes Apps Mobile

//Convert Currency
Route::get('/fwasdevelopers/admin-manager/manager-projects/app-mobile/convert-currency','CurrencyController@ShowCoins');
Route::get('/fwasdevelopers/admin-manager/manager-projects/app-mobile/convert-currency/create','CurrencyController@CreateCoin');
Route::post('/fwasdevelopers/admin-manager/manager-projects/app-mobile/convert-currency/store','CurrencyController@StoreCoin');
Route::get('/fwasdevelopers/admin-manager/manager-projects/app-mobile/convert-currency/edit/{id}','CurrencyController@EditCoin');
Route::post('/fwasdevelopers/admin-manager/manager-projects/app-mobile/convert-currency/update/{id}','CurrencyController@UpdateCoin');
Route::get('/fwasdevelopers/admin-manager/manager-projects/app-mobile/convert-currency/delete/{id}','CurrencyController@DestroyCoin');


});

Route::get('/fwdadmin/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/fwdadmin/login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Models/Blog.php
<?php

namespace freelance_web\Models;

use Spatie\Sluggable\Slug;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
use Jenssegers\Date\Date;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasSlug;
  
    protected $table = 'blog';

    public function getSlugOptions() : SlugOptions
    {
      return SlugOptions::create()
      ->generateSlugsFrom('heading')
      ->saveSlugsTo('slug');
    }

    public function scopeName($query,$name){
      if (trim($name) == "") {
        }else
        $query->where('heading',"LIKE","%$name%");
    }

    public function getCreatedAtAttribute($date){
      return new Date($date);
    }

}

resources/views/about.blade.php
@extends('layouts.freelance')

@section('title', '¿Quiénes somos? | Freelance Developers')
@section('urlcanonical','https://fdevelopershn.com/nosotros')
@section('description', 'Somos una empresa altamente calificada y especializada en cada campo del desarrollo web, móvil
y marketing digital. Brindamos soluciones creativas e innovadoras, ofreciendo los mejores servicios en desarrollo informático.')
@section('keywords', ' Páginas web Honduras, sitios web dinámicos, desarrollo móvil, servicios de marketing digital')
{{-- For FB Meta tags --}}
@section('ogtitle', 'Descubre por que somos lo que necesitas, desarrollo web y móvil | FDevelopers')
@section('ogurl', 'https://fdevelopershn.com/nosotros')
@section('ogimage', 'https://fdevelopershn.com/img/team-acerca-de.webp')
@section('ogdescription', 'Los mejores servicios en desarrollo web, mobile y marketing digital en Honduras')
{{-- End For FB Meta tags --}}

@section('content')
  <div class="parallax-container text-center-img">
    <h1 class="center-align title-parallax-spacing font-weight-parallax">Freelance Developers</h1>
    <div class="parallax"><img src="/img/team-acerca-de.webp" alt="team acerca de freelance developers"></div>
  </div>
  <div class="content-wrapper">
    <div class="container">
      <div class="background-white">
          <div class="post">
            <div class="row">
              <div class="col s12">
                <h5 class="center-align no-margin sub-title">Conoce más</h5>
                <h2 class="center-align color-darkgray title no-margin">Sobre Nosotros</h2>
                <div class="separate"></div>
                <div class="row">
                    <div class="col l12">
                      <p class="center-align color-darkgray">Somos una agencia altamente calificada y especializada en cada campo del desarrollo web,
                      móvil y marketing digital en Honduras. Brindamos soluciones creativas e innovadoras, ofreciendo los mejores servicios en desarrollo
                      informático, utilizando las últimas tecnologías en tendencias, con el fin de incrementar el rendimiento
                      del proyecto y sobrepasar las expectativas de nuestros clientes.</p>
                    </div>
                </div>
                <div class="row">
                  <div class="col s12 m6 l4">
                    <div class="card hoverable medium">
                      <div class="card-image">
                        <img class="img-padding-full" src="/img/book-laptop-html-css.webp" alt="libro html css y laptop">
                      </div>
                      <div class="avatar">
                        <img class="img-avatar" src="/img/geo.png" alt="fotografia de uno de los fundadores">
                      </div>
                      <div class="card-content top-text-card-medium center-align">
                        <span class="card-profile-title color-darkgray">Gerson Alvarez</span>
                        <span class="card-profile-subtitle">Fundador/Front-end Developer</span>
                        <p class="card-profile-p color-darkgray">Ingeniero en Ciencias de la Computación.</p>
                        <div class="card-profile-icon">
                          <a href="https://www.facebook.com/gerson.alvarez.39"><img class="icon" src="/img/facebook-gray.png" alt="Icono facebook"></a>
                          <a href="https://www.linkedin.com/in/gerson-geovany-alvarez-flores-53a4b5162/"><img class="icon" src="/img/in.png" alt="Icono linkedin"></a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col s12 m6 l4">
                    <div class="card hoverable medium">
                      <div class="card-image">
                        <img class="img-padding-full" src="/img/book-laptop-html-css.webp" alt="libro html css y laptop">
                      </div>
                      <div class="avatar">
                        <img class="img-avatar" src="/img/alejandro.png" alt="fotografia de uno de los fundadores">
                      </div>
                      <div class="card-content top-text-card-medium center-align">
                        <span class="card-profile-title color-darkgray">Alejandro Tejada</span>
                        <span class="card-profile-subtitle">Fundador/Back-end Developer</span>
                        <p class="card-profile-p color-darkgray">Ingeniero en Ciencias de la Computación.</p>
                        <div class="card-profile-icon">
                          <a href="https://www.facebook.com/profile.php?id=100001285121518"><img class="icon" src="/img/facebook-gray.png" alt="Icono facebook"></a>
                          <a href="https://www.linkedin.com/in/jose-alejandro-tejada-guardado-029a61159/"><img class="icon" src="/img/in.png" alt="Icono linkedin"></a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col s12 m6 l4">
                    <div class="card hoverable medium">
                      <div class="card-image">
                        <img class="img-padding-full" src="/img/book-laptop-html-css.webp" alt="libro html css y laptop">
                      </div>
                      <div class="avatar">
                        <img class="img-avatar" src="/img/jonathan.png" alt="fotografia de uno de los fundadores">
                      </div>
                      <div class="card-content top-text-card-medium center-align">
                        <span class="card-profile-title color-darkgray">Jonathan Franco</span>
                        <span class="card-profile-subtitle">Fundador/Back-end Developer</span>
                        <p class="card-profile-p color-darkgray">Ingeniero en Ciencias de la Computación.</p>
                        <div class="card-profile-icon">
                          <a href="https://www.facebook.com/DavidP94"><img class="icon" src="/img/facebook-gray.png" alt="Icono facebook"></a>
                          <a href="https://www.linkedin.com/in/jonathan-d-franco-09848b43/"><img class="icon" src="/img/in.png" alt="Icono linkedin"></a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
  <div class="background-gray">
    <div class="content-wrapper">
      <div class="post container">
        <div class="row">
          <div class="col s12 m12 l6">
            <div id="mis-vis"></div>
          </div>
          <div class="col s12 m12 l6">
            <section class="mision padding-top">
              <h3 class="center-align color-darkgray title no-margin">Misión</h3>
              <div class="separate"></div>
              <p class="justify-align">Brindar los mejores servicios en desarrollo informático a las empresas,
              emprendedores y autónomos con el fin de incrementar su competitividad en el mundo del internet, manteniendo una
              relación cercana y directa con el cliente ofreciendo las soluciones más innovadoras a precios muy competitivos.</p>
            </section>
            <section class="vision">
              <h3 class="center-align color-darkgray title no-margin">Visión</h3>
              <div class="separate"></div>
              <p class="justify-align">Ser una empresa confiable, sólida y rentable que brinde servicios en
              desarrollo informático de primera categoría, convirtiéndonos en la mejor alternativa a nivel nacional e
              internacional, garantizando calidad en cada servicio que brindemos a nuestros clientes.</p>
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="background-white">
    <div class="content-wrapper">
      <div class="post container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h2 class="center-align color-darkgray title no-margin">Nuestros valores</h2>
            <div class="separate"></div>
            <p class="center-align color-darkgray bold-content">Pasión, Compromiso, Innovación, Calidad y Honestidad.</p>
            <p class="center-align color-darkgray">El éxito de nuestros clientes es también el nuestro, por eso damos más del 100%
            con cada proyecto que nos confían. Desde microempresas hasta corporaciones, nosotros podemos satisfacer las necesidades
            de su negocio.</p>
            <p class="center-align color-darkgray bold-content">"Innovación y Calidad Garantizada"</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="parallax-container hide-on-small-parallax-mobile">
    <div class="post padding-content-parallax">
      <h3 class="center-align white-text title">¿Cómo trabajamos?</h3>
      <div class="row container">
        <div class="col s6 m4 l2 hide-on-small-and-down-box-homework">
          <div class="process-box center-align">
            <i class="small material-icons">local_cafe</i>
            <p>Reunión</p>
          </div>
        </div>
        <div class="col s6 m4 l2 hide-on-small-and-down-box-homework">
          <div class="process-box center-align">
            <i class="small material-icons">lightbulb_outline</i>
            <p>Planificación</p>
          </div>
        </div>
        <div class="col s6 m4 l2 hide-on-small-and-down-box-homework">
          <div class="process-box center-align">
            <i class="small material-icons">color_lens</i>
            <p>Diseño</p>
          </div>
        </div>
        <div class="col s6 m4 l2 hide-on-small-and-down-box-homework">
          <div class="process-box center-align">
            <i class="small material-icons">developer_mode</i>
            <p>Desarrollo</p>
          </div>
        </div>
        <div class="col s6 m4 l2 hide-on-small-and-down-box-homework">
          <div class="process-box center-align">
            <i class="small material-icons">verified_user</i>
            <p>Pruebas</p>
          </div>
        </div>
        <div class="col s6 m4 l2 hide-on-small-and-down-box-homework">
          <div class="process-box center-align">
            <i class="small material-icons">archive</i>
            <p>Entrega</p>
          </div>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="/img/proceso-trabajo-laptop-book.webp" alt="proceso de trabajo web, laptop y libro de apuntes"></div>
  </div>
  <div class="content-wrapper">
    <div class="post container">
      <h3 class="center-align color-darkgray p-phrase">Descubre por qué somos lo que necesitas.</h3>
      <div class="center-align social-media-padding-top"><a href="/contactanos"><button class="button">Empecemos tu Proyecto</button></a></div>
    </div>
  </div>
@endsection

resources/views/blog.blade.php
@extends('layouts.freelance')

@section('title', 'Blog sobre tecnología, internet y programación')
@section('urlcanonical','https://fdevelopershn.com/blog')
@section('description', 'Mantente actualizado con lo que sucede en el mundo informático a través de nuestro Blog
donde compartimos lo mejor sobre tecnología, internet y programación.')
@section('keywords', 'blog, tecnología, internet, programación')
{{-- For FB Meta tags --}}
@section('ogtitle', 'Blog sobre tecnología, internet y programación | FDevelopers')
@section('ogurl', 'https://fdevelopershn.com/blog')
@section('ogimage', 'https://fdevelopershn.com/img/blog-web-freelance.webp')
@section('ogdescription', 'Blog sobre tecnología, internet y programación')
{{-- End For FB Meta tags --}}

@section('content')
<div class="parallax-container text-center-img">
  <div class="row">
    <div class="col l12">
      <h1 class="center-align title-parallax-spacing bold-content">Blog</h1>
      <p class="center-align p-content">Tecnología, Internet y programación.</p>
    </div>
  </div>
  <div class="parallax"><img src="img/blog-web-freelance.webp" alt="blog web freelance developers"></div>
</div>
<div class="background-white">
  <div class="content-wrapper">
    <div class="post container">
      <div class="row">
        @foreach ($posts as $post)
        <div class="col s12 m6 l4">
          <a href="/blog/{{ $post->slug }}">
            <div class="card-blog medium hoverable">
              <div class="card-blog-image">
                <img src="img/blog/{{ $post->image }}">
                <div class="date">
                  <div class="day">{{ strftime("%d",strtotime($post->created_at)) }}</div>
                  <div class="month">{{ strftime("%b",strtotime($post->created_at)) }}</div>
                </div>
                <h2 class="card-blog-title">{{ $post->heading }}</h2>
              </div>
              <div class="card-blog-content">
                <h2>{{ $post->title }}</h2>
                {{ strip_tags(html_entity_decode(str_limit( $post->content, 90))) }}
                <div class="card-blog-action">
                  <p class="card-blog-p"><i class="tiny material-icons">access_time</i>
                    {{ ($post->created_at)->diffForHumans() }}</p>
                </div>
              </div>
            </div>
          </a>
        </div>
        @endforeach
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/email.blade.php
<img src="https://fdevelopershn.com/img/logo.png"  alt="freelance">

<h3>
Name: </h3>

<h5>
  {{ $name }}
</h5>



<h3>
Telefono:</h3> <h5>{{ $telephone }}
</h5>

<h3>
Email: </h3> <h5>{{ $email }}
</h5>

<h3>
  Company:</h3> <h5> {{ $company }}
  </h5>

<h3>
Message:</h3> <h5> {{ $user_message }}
</h5>

<h3>
  Social:</h3> <h5> {{ $social }}
  </h5>

resources/views/home.blade.php
@extends('layouts.freelance')

@section('title', 'Diseño, desarrollo de páginas web y marketing digital en Honduras')
@section('urlcanonical','https://fdevelopershn.com/')
@section('description', 'Contamos con expertos en desarrollo web en Honduras, que pueden ayudarte a desarrollar sitios web modernos y atractivos a precios muy competitivos.')
@section('keywords', 'Freelance, desarrollo web, paginas web dinámicas, aplicaciones web, app móviles, servicios de
maquetación web')
{{-- For FB Meta tags --}}
@section('ogtitle', 'Desarrollo web, móvil y servicios de marketing digital en Honduras | FDevelopers')
@section('ogurl', 'https://fdevelopershn.com')
@section('ogimage', 'https://fdevelopershn.com/img/proceso-trabajo-laptop-book.webp')
@section('ogdescription', 'Desarrollo de sitios web, aplicaciones móviles y marketing digital en Honduras')
{{-- End For FB Meta tags --}}

@section('content')
<div class="slider">
  <ul class="slides">
    @foreach ($detail_sliders as $detail_slider)
    <li>
      <img src="/img/sliders/{{ $detail_slider->image_slider }}" alt="{{ $detail_slider->alt_image  }}">
      <!-- random image -->
      <div class="caption {{ $detail_slider->text_position }}-align">
        <h1 class="bold-title-slider">{{ $detail_slider->titulo_slider }}</h1>
        <p class="p-slider-content">{{ $detail_slider->description_slider }}</p>
      </div>
    </li>
    @endforeach
  </ul>
</div>
<div class="background-white">
  <div class="content-wrapper">
    <div class=" post container">
      <h5 class="center-align no-margin sub-title">Conoce más</h5>
      <h3 class="center-align color-darkgray title no-margin">Sobre Nosotros</h3>
      <div class="separate"></div>
      <div class="row">
        <div class="col s12 m12 l12">
          <p class="center-align color-darkgray">Somos una agencia altamente calificada y especializada en cada campo del desarrollo web,
          móvil y marketing digital en Honduras. Brindamos soluciones creativas e innovadoras, ofreciendo los mejores servicios en desarrollo
          informático, utilizando las últimas tecnologías en tendencias, con el fin de incrementar el rendimiento
          del proyecto y sobrepasar las expectativas de nuestros clientes.</p>
          <div class="center-align"><a href="/nosotros"><button class="button">Ver Más...</button></a></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="background-gray">
  <div class="content-wrapper">
    <div class="post container">
      <div class="row">
        <div class="col s12 m12 l6">
          <div id="site-web"></div>
        </div>
        <div class="col s12 m12 l6">
          <h5 class="center-align no-margin sub-title padding-top">Importancia</h5>
          <h3 class="center-align color-darkgray title no-margin">Sitios web</h3>
          <div class="separate"></div>
          <p class="justify-align color-darkgray">Para una empresa, lo mejor es estar donde están los usuarios y estos, en su
          gran mayoría, están en línea. Este aumento en el uso de Internet presenta potencial para todos los tipos de empresas,
          siempre que puedan encontrar el momento en que su público está en línea.</p>
          <p class="justify-align color-darkgray">Freelance Developers cuenta con expertos que pueden desarrollar la estrategia
          que tu empresa tanto necesita, desde página web hasta redes sociales y proveer a tu negocio con todas las herramientas
          para convertirte en líder de la industria en la nueva era digital.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="background-white">
  <div class="content-wrapper">
    <div class="post container">
      <h5 class="center-align no-margin sub-title">Nuestros</h5>
      <h3 class="center-align color-darkgray title no-margin">Servicios de Desarrollo</h3>
      <div class="separate"></div>
      <p class="center-align color-darkgray">Ofrecemos una gama completa de servicios de desarrollo web y móvil. Nuestro
        objetivo es proporcionar soluciones creativas e innovadoras en desarrollo informático que ayuden a su empresa a crecer y
        desarrollarse rápidamente.</p>
      <div class="row icon-center-div center-align padding-top hide-on-small-and-down-icon-services">
        @foreach ($services as $service)
        <div class="col s6 l3 hide-on-small-and-down-row-padding">
          <img class="img-icon padding-bottom-icon" src="/img/services/{{ $service->image_service }}"
            alt="Icono desarrollo web">
          <p class="no-margin color-darkgray">{{ $service->name_service }}</p>
        </div>
        @endforeach
      </div>
      <div class="center-align padding-top"><a href="/servicios"><button class="button">Ver Más...</button></a></div>
    </div>
  </div>
</div>
<div class="background-gray">
  <div class="content-wrapper">
    <div class="post container">
      <div class="row">
        <div class="col s12 m12 l6">
          <h5 class="center-align no-margin sub-title">Sitios web</h5>
          <h3 class="center-align color-darkgray title no-margin">Adaptables a móviles</h3>
          <div class="separate"></div>
          <p class="justify-align color-darkgray">Cada vez más y más personas están visitando los sitios web desde un smartphone.
          Las web responsive se han convertido en el estándar de la industria, y los propietarios de sitios web no quieren
          quedarse atrás.</p>
          <p class="justify-align color-darkgray">El diseño web adaptable a móviles trata de proporcionar al usuario la mejor
          experiencia posible, no importa el dispositivo que esté utilizando. Se trata de hacer más fácil la navegación
          al usuario.</p>
          <p class="justify-align color-darkgray">En Freelance Developers podemos dar ese carácter moderno que tu empresa necesita
          para poder adaptarse a los consumidores de la actualidad.</p>
        </div>
        <div class="col s12 m12 l6">
          <div id="web-responsive"></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="background-white">
  <div class="content-wrapper">
    <div class="post container">
      <h5 class="center-align no-margin sub-title">Nuestro</h5>
      <h3 class="center-align color-darkgray title no-margin">Portafolio</h3>
      <div class="separate"></div>
      <div class="row">
        @foreach ($projects as $project)
        <div class="col s12 m6 l4">
          <div class="card small hoverable">
            <div class="card-image waves-effect waves-block waves-light">
              <img class="activator" src="/img/projects/{{ $project->image_project }}"
                alt="computadora mac que muestra el sitio web de freelance">
            </div>
            <div class="card-content-portfolio">
              <div class="border-title">
                <span class="card-title-portfolio"><a href="{{ $project->link_project }}">{{ $project->name_project }}<i
                      class="material-icons right">more_vert</i></a></span>
                @foreach ($services as $service)
                @if ($service->id==$project->id_service)
                <span class="tag-title">{{ $service->name_service }}</span>
                @endif
                @endforeach
              </div>
            </div>
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4">{{ $project->name_project }}<i
                  class="material-icons right">close</i></span>
              <p>{{ $project->content_project }}</p>
            </div>
          </div>
        </div>
        @endforeach
      </div>
      <div class="center-align"><a href="/portafolio"><button class="button">Ver Más...</button></a></div>
    </div>
  </div>
</div>
<div class="background-gray">
  <div class="content-wrapper">
    <div class="post container">
      <div class="row">
        <div class="col s12 m12 l6">
          <div id="bene-freelance"></div>
        </div>
        <div class="col s12 m12 l6">
          <h3 class="left-align color-darkgray padding-top">¿Qué obtienes al adquirir un sitio web con Freelance Developers?</h3>
          <div class="separate"></div>
          <ul class="color-darkgray left-align">
            <li><i class="tiny material-icons">public</i>Dominio por un año.</li>
            <li><i class="tiny material-icons">dns</i>Hospedaje web por un año.</li>
            <li><i class="tiny material-icons">email</i>Cuentas de correo.</li>
            <li><i class="tiny material-icons">devices</i>Sitio web adaptable a móviles.</li>
            <li><i class="tiny material-icons">build</i>Soporte gratis durante 1 mes.</li>
            <li><i class="tiny material-icons">security</i>Certificado de seguridad SSL.</li>
            <li><i class="tiny material-icons">chrome_reader_mode</i>Formulario de contacto.</li>
            <li><i class="tiny material-icons">show_chart</i>Google Analytics.</li>
            <li><i class="tiny material-icons">search</i>SEO básico.</li>
            <li><i class="tiny material-icons">create</i>Sitio autoadministrable.</li>
            <li><i class="tiny material-icons">storage</i>Base de datos.</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="background-white">
  <div class="content-wrapper">
    <div class="post container">
      <h5 class="center-align no-margin sub-title">Últimas noticias</h5>
      <h2 class="center-align color-darkgray title no-margin">Nuestro blog</h2>
      <div class="separate"></div>
      <div class="row">
        @foreach ($posts as $post)
        <div class="col s12 m6 l4">
          <a href="/blog/{{ $post->slug }}">
            <div class="card-blog medium hoverable">
              <div class="card-blog-image">
                <img src="img/blog/{{ $post->image }}" alt="{{ $post->heading  }}">
                <div class="date">
                  <div class="day">{{ strftime("%d",strtotime($post->created_at)) }}</div>
                  <div class="month">{{ strftime("%b",strtotime($post->created_at)) }}</div>
                </div>
                <h2 class="card-blog-title">{{ $post->heading }}</h2>
              </div>
              <div class="card-blog-content">
                <h2>{{ $post->title }}</h2>
                {{ strip_tags(html_entity_decode(str_limit( $post->content, 90))) }}
                <div class="card-blog-action">
                  <p class="card-blog-p"><i class="tiny material-icons">access_time</i>
                    {{ ($post->created_at)->diffForHumans() }}</p>
                </div>
              </div>
            </div>
          </a>
        </div>
        @endforeach
      </div>
      <div class="center-align"><a href="/blog"><button class="button">Ver Más...</button></a></div>
    </div>
  </div>
</div>
@endsection